### ISSUE TITLE
Default channels

### ISSUE THREAD

**Issue by Informatic** [rodorgas/django-rocketchat-auth#1]
Hi!
This is issue is not strictly related to this specific project.
I've done the same kind of integration, but with flask & flask-security. Right now the only problem I'm sumbling upon is that users are not joining default channels, even though I'm doing exactly the same operation as Your code ("$addToSet" thing...) and it still does not seem to work. (username is added to the set, but user is not joining the channel)

I'm not a mongo/nodejs guy myself and I haven't really debugged it much, so maybe i'm missing something, or it's just a bug in Rocketchat.

Does that operation work for you properly?

**Comment by rodorgas** [comment]
It used to work. Now, we also have to add a new document in rocketchat_subscription.

Basically, you will add a subscription for each default room, please [check the details in my updated code](https://github.com/rodorgas/django-rocketchat-auth/blob/37405bbe677f7b4c921c3b44f429c930a0864f73/rocketchat_auth/views.py#L95).

**Comment by Informatic** [comment]
That's great, thank you very much!
